post_install() {
  cat <<EOF
==> You should copy /opt/graphite/webapp/graphite/local_settings.py.example
==> to /opt/graphite/webapp/graphite/local_settings.py and edit
==> it to reflect your database settings and then run:
==>
==>     python /opt/graphite/webapp/graphite/manage.py syncdb
==>
==> to setup the required Graphite database and tables.
==>
==> A WSGI compliant server like uWSGI, Gunicorn, or Apache with mod_wsgi
==> needs to be configured.
EOF
}
